from include import *

# Liste des identifiants d'actions
stocks = {
    "airbus": "AIR.PA",      # CAC40
    "amundi": "AMUN.PA",
    "alstom": "ALO.PA",
    "atos": "ATO.PA",
    "bouygues": "EN.PA",
    "bnp_paribas": "BNP.PA",
    "capgemini": "CAP.PA",
    "credit_agricole": "ACA.PA",
    "dassault_systemes": "DSY.PA",
    "essilorluxottica": "EL.PA",
    "kering": "KER.PA",
    "l'oreal": "OR.PA",
    "orange": "ORAN",
    "renault": "RNO.PA",
    "societe_generale": "GLE.PA",
    "sanofi": "SAN.PA",
    "schneider_electric": "SU.PA",
    "saint_gobain": "SGO.PA",
    "totalenergies": "TTE.PA",
    "vinci": "DG.PA",
    "vivendi": "VIV.PA",
    "tesla": "TSLA",             # NASDAQ
    "microsoft": "MSFT",
    "apple": "AAPL",
    "amazon": "AMZN",
    "facebook": "FB",
    "alphabet": "GOOGL",
    "netflix": "NFLX",
    "paypal": "PYPL",
    "intel": "INTC",
    "cisco": "CSCO",
    "qualcomm": "QCOM",
    "adobe": "ADBE",
    "amd": "AMD",
    "nvidia": "NVDA",
    "twitter": "TWTR",
    "uber": "UBER",
    "snap": "SNAP",
    "spotify": "SPOT",
    "tesla": "TSLA",
    "nike": "NKE",
    "starbucks": "SBUX",
    "coca-cola": "KO",
    "pepsi": "PEP",
    "mcdonald's": "MCD",
    "disney": "DIS",
    "visa": "V",
    "mastercard": "MA",
    "walmart": "WMT",
    "target": "TGT",
    "costco": "COST",
    "home_depot": "HD",
    "lowe's": "LOW",
    "boeing": "BA",
    "lockheed_martin": "LMT",
    "raytheon": "RTX",
    "northrop_grumman": "NOC",
    "general_dynamics": "GD",
    "united_technologies": "UTX",
    "honeywell": "HON",
    "general_electric": "GE",
    "exxon_mobil": "XOM",
    "chevron": "CVX",
    "shell": "RDS-A",
    "bp": "BP",
    "total": "TOT",
    "pfizer": "PFE",
    "johnson_&_johnson": "JNJ",
    "novartis": "NVS",
}
